### ISSUE TITLE
Ruby 2.1.1 won't compile in Ubuntu trusty

### ISSUE THREAD

**Issue by rodowi** [mxabierto/adela#135]
http://stackoverflow.com/questions/23418227/rbenv-error-compiling-ruby-2-1-1

Y U NO UPGRADE TO 2.1.2?

**Comment by rodowi** [comment]
testing...

**Comment by rodowi** [comment]
```zsh
➜  adela git:(update-gemfile) ✗ rbenv local 2.1.2
➜  adela git:(update-gemfile) ✗ git status
On branch update-gemfile
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Gemfile

no changes added to commit (use "git add" and/or "git commit -a")
➜  adela git:(update-gemfile) ✗ ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
➜  adela git:(update-gemfile) ✗ bundle install
Fetching source index from http://rubygems.org/
Installing rake 10.3.1
Installing i18n 0.6.9

```

**Comment by rodowi** [comment]
```zsh
Installing database_cleaner 1.2.0
Installing debugger-linecache 1.2.0
Installing debugger-ruby_core_source 1.3.2

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/rodolfo/.rbenv/versions/2.1.2/bin/ruby extconf.rb 
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/rodolfo/.rbenv/versions/2.1.2/bin/ruby
/Users/rodolfo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/fileutils.rb:1573:in `stat': No such file or directory @ rb_file_s_stat - ./212/ruby_debug.h (Errno::ENOENT)
	from /Users/rodolfo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/fileutils.rb:1573:in `block in fu_each_src_dest'
	from /Users/rodolfo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/fileutils.rb:1587:in `fu_each_src_dest0'
	from /Users/rodolfo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/fileutils.rb:1571:in `fu_each_src_dest'
	from /Users/rodolfo/.rbenv/versions/2.1.2/lib/ruby/2.1.0/fileutils.rb:399:in `cp'
	from extconf.rb:83:in `block in <main>'
	from extconf.rb:82:in `each'
	from extconf.rb:82:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/rodolfo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/debugger-1.6.6 for inspection.
Results logged to /Users/rodolfo/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-13/2.1.0-static/debugger-1.6.6/gem_make.out
An error occurred while installing debugger (1.6.6), and Bundler cannot
continue.
Make sure that `gem install debugger -v '1.6.6'` succeeds before bundling.
➜  adela git:(update-gemfile) ✗
```

**Comment by rodowi** [comment]
debugger no es compatible con 2.1.2

http://stackoverflow.com/questions/24395453/gem-install-debugger-error
https://github.com/cldwalker/debugger/issues/125#issuecomment-43353446

Alguna razón por la que se use debugger? @abisosa @juanpabloe 

o actualizamos a byebug?

**Comment by juanpabloe** [comment]
No hay razón específica. Es solo una console tool.
Se podría actualizar a byebug

**Comment by rodowi** [comment]
en proceso...

**Comment by rodowi** [comment]
ya está jalando con byebug y ruby 2.1.2

**Comment by rodowi** [comment]
hay que actualizar travis no?

**Comment by juanpabloe** [comment]
![johnsnow](http://www.scifistream.com/wp-content/uploads/lord-snow1.jpg)

**Comment by rodowi** [comment]
All is well, your Grace

**Comment by rodowi** [comment]
conflicto de rake 10.3.1 con ruby 2.1.2

```zsh
Step 16 : RUN bundle install --without development
 ---> Running in c108ece574d3
Fetching source index from http://rubygems.org/
sudo: no tty present and no askpass program specified

Bundler::GemspecError: Could not read gem at /usr/local/lib/ruby/gems/2.1.0/cache/rake-10.3.1.gem. It may be corrupted.
An error occurred while installing rake (10.3.1), and Bundler cannot continue.
Make sure that `gem install rake -v '10.3.1'` succeeds before bundling.
2015/01/28 23:41:20 The command [/bin/sh -c bundle install --without development] returned a non-zero code: 5
```

vamos a probar con 2.1.5

**Comment by rodowi** [comment]
eh mijo, ha de ser el Gemfile.lock

**Comment by rodowi** [comment]
FUUUUUUUU

```zsh
Step 16 : RUN bundle install --without development
 ---> Running in bfee8a8729e7


sudo: no tty present and no askpass program specified

Bundler::GemspecError: Could not read gem at /usr/local/lib/ruby/gems/2.1.0/cache/rake-10.4.2.gem. It may be corrupted.
An error occurred while installing rake (10.4.2), and Bundler cannot continue.
Make sure that `gem install rake -v '10.4.2'` succeeds before bundling.
2015/01/28 23:50:53 The command [/bin/sh -c bundle install --without development] returned a non-zero code: 5
core@localhost ~/adela $ 
```

**Comment by rodowi** [comment]
El trip con rake era que estaba corriendo como root en el docker container

`su -c "..." -l web` lo arregló
