### ISSUE TITLE
Error al actualizar el plan de apertura

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/adela#802]
Al momento de actualizar el Plan de Apertura se muestra la pantalla de error

![screen shot 2016-03-02 at 9 24 35 am](https://cloud.githubusercontent.com/assets/2633527/13465161/ff9fe2a2-e059-11e5-9ae7-8d8fc9c64a60.png)

En el log no hay mensajes de error asociados que nos puedan ayudar a saber que paso

```
2016-03-02T15:21:12.643587+00:00 app[web.1]: Started POST "/plan-de-apertura" for 189.203.188.80 at 2016-03-02 15:21:12 +0000
2016-03-02T15:21:12.645904+00:00 app[web.1]: Processing by OpeningPlanController#create as HTML
2016-03-02T15:21:12.646718+00:00 app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"PmYua+VQU1eISNNtR3uWspikspY/eq4ZJ5fMkDy+icxTtguYPK7c21amr4Z8QnSc7rRf68RhSR6Pnf+bpXdTUw==", "organization"=>{"opening_plans_attributes"=>{"0"=>{"_destroy"=>"0", "name"=>"Cartera de Inversión", "description"=>"Listado de Programas y Proyectos de Inversión de la Obra Pública Abierta", "accrual_periodicity"=>"R/P3M", "publish_date"=>"2015-09-30", "id"=>"14553"}, "1"=>{"_destroy"=>"0", "name"=>"Presupuesto de Egresos de la Federación", "description"=>"Listado que describe la cantidad, la forma de distribución y el destino de los recursos públicos de los tres poderes de los organismos autónomos, como el Instituto Federal Electoral y la Comisión Nacional de los Derechos Humanos, así como las transferencias a los gobiernos estatales y municipales", "accrual_periodicity"=>"R/P1Y", "publish_date"=>"2015-05-27", "id"=>"14554"}, "2"=>{"_destroy"=>"0", "name"=>"Proyecto de Presupuesto de Egresos", "description"=>"Listado con la distribución y objetivos de los recursos públicos para el próximo año  fiscal ", "accrual_periodicity"=>"R/P1Y", "publish_date"=>"2015-05-27", "id"=>"14555"}, "3"=>{"_destroy"=>"0", "name"=>"Ramo 23 \"Provisiones salariales y económicas\"", "description"=>"Listado de datos del otorgamiento de recursos a Entidades Federativas y Municipios a través de fondos específicos", "accrual_periodicity"=>"R/P3M", "publish_date"=>"2015-05-27", "id"=>"14556"}, "4"=>{"_destroy"=>"0", "name"=>"Cuenta Pública", "description"=>"Listado con información contable, presupuestaria y programática de los tres Poderes de la Unión de los órganos constitucionalmente autónomos", "accrual_periodicity"=>"R/P1Y", "publish_date"=>"2015-05-27", "id"=>"14557"}, "5"=>{"_destroy"=>"0", "name"=>"Estadísticas Oportunas de Finanzas Públicas.", "description"=>"Listado con un conjuto de datos sobre indicadores fiscales como balances, ingresos, gastos, financiamiento y deuda pública del Gobierno Federal, entidades paraestatales no financieras, entidades paraestatales financieras, sector público presupuestario y sector público federal, así como transferencias federales a Estados y Municipios", "accrual_periodicity"=>"R/P1M", "publish_date"=>"2015-05-27", "id"=>"14558"}, "6"=>{"_destroy"=>"0", "name"=>"Avances en los indicadores de desempeño", "description"=>"Listado que ofrece información sobre los indicadores del desempeño  de los programas presupuestarios permiten identificar los avances en el cumplimiento de las metas establecidas para cada uno", "accrual_periodicity"=>"R/P3M", "publish_date"=>"2015-05-27", "id"=>"14559"}, "7"=>{"_destroy"=>"0", "name"=>"Proyectos Entidades Federativas", "description"=>"Listado que contiene la información que reportan las entidades federativas, municipios y demarcaciones territoriales del Distrito Federal sobre los avances físicos y financieros de los programas y proyectos de inversión que llevan a cabo con recursos que les transfiere la Federación a través de aportaciones federales, subsidios y convenios", "accrual_periodicity"=>"R/P3M", "publish_date"=>"2015-05-27", "id"=>"14560"}}}, "button"=>"", "locale"=>"es"}
2016-03-02T15:21:12.868788+00:00 app[web.1]:   app/models/distribution.rb:41:in `sort'
2016-03-02T15:21:12.868789+00:00 app[web.1]:   app/models/distribution.rb:41:in `update_dataset_metadata'
2016-03-02T15:21:12.868790+00:00 app[web.1]:   app/commands/catalog_datasets_generator.rb:71:in `map'
2016-03-02T15:21:12.868790+00:00 app[web.1]:   app/commands/catalog_datasets_generator.rb:71:in `create_new_distributions'
2016-03-02T15:21:12.871729+00:00 heroku[router]: at=info method=POST path="/plan-de-apertura" host=adela.datos.gob.mx request_id=99fbfb5f-be24-4850-baf5-5e061bb31001 fwd="189.203.188.80" dyno=web.1 connect=26ms service=285ms status=500 bytes=1495
```

**Comment by carlosmaya** [comment]
resuelto con #803
